### ISSUE TITLE
Usage in README is not working

### ISSUE THREAD

**Issue by radaiming** [luckymarmot/API-Flow#46]
Hi,

I'm trying to import postman's data, I did as README told, clone the repo, run "make install" with exit code 0, but there's no "./node_modules/lib/api-flow.js" file, if I try to use "./bin/api-flow.js", error comes:

\> node bin/api-flow.js /tmp/v2.json -f postman-2 -t raml
/tmp/tmp.jDw4AygtOF/API-Flow/lib/parsers/swagger/Parser.js:105
                throw new Error(m + _tv2.default.error);
                ^

Error: Invalid Swagger File (invalid schema / version < 2.0):
ValidationError: Invalid type: string (expected object)
    at SwaggerParser.parse (/tmp/tmp.jDw4AygtOF/API-Flow/lib/parsers/swagger/Parser.js:105:23)
    at FlowCLI.run (/tmp/tmp.jDw4AygtOF/API-Flow/lib/runners/flow-node.js:269:34)
    at Object.<anonymous> (/tmp/tmp.jDw4AygtOF/API-Flow/bin/api-flow.js:4:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)

**Comment by JonathanMontane** [comment]
Woops, this is my fault. It seems that I merged the Readme before the PR it should have been attached to (which was massive). 

In any case, it should be fixed now.
try to do a `git pull origin master` and `make install`, and you should be good to go.

**Comment by radaiming** [comment]
Thanks for you fix :)
